# Generated by Django 5.2.4 on 2025-07-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_users_name_users_first_name_users_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='promotions_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
