# Generated by Django 5.2.4 on 2025-07-18 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_users_promotions_opt_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='users',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='users',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='shipping_address',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=20)),
                ('expiration_date', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
