# Generated by Django 5.2.4 on 2025-07-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_users_card_number_remove_users_card_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='City', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='USA', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='Georgia', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='Street', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='30601', max_length=20),
            preserve_default=False,
        ),
    ]
