# Generated by Django 5.2.4 on 2025-07-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_address_options_alter_address_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcard',
            name='card_number',
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='card_number_hash',
            field=models.CharField(default='1223', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='last4',
            field=models.CharField(default='1233', max_length=4),
            preserve_default=False,
        ),
    ]
