# Generated by Django 5.2.4 on 2025-07-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_paymentcard_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='cvv_hash',
            field=models.CharField(default='', help_text='SHA-256 hash of the card CVV', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='name',
            field=models.CharField(default='name', help_text='Name on the card', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='zipcode',
            field=models.CharField(default='11111', help_text='Billing ZIP/postal code', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='expiration_date',
            field=models.CharField(help_text='Expiration date in MM/YY format, e.g. 02/23', max_length=5),
        ),
    ]
