# Generated by Django 5.2.3 on 2025-06-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=100)),
                ('publication_year', models.PositiveIntegerField()),
                ('cover_image', models.URLField()),
                ('quantity_in_stock', models.PositiveIntegerField()),
                ('minimum_threshold', models.PositiveIntegerField()),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
