# Generated by Django 5.2.3 on 2025-06-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
