# Generated by Django 5.2.3 on 2025-06-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
